# Generated by Django 4.1.7 on 2023-03-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_customer_email_customer_name_alter_pizza_crust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.customer_email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.customer_name'),
        ),
    ]
