# Generated by Django 4.1.7 on 2023-03-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_alter_addons_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='crust',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Addons',
        ),
        migrations.DeleteModel(
            name='Crust',
        ),
    ]
