# Generated by Django 4.1.7 on 2023-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_delete_customer_remove_pizza_addons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(max_length=100),
        ),
    ]
